# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 胜彬的博客
email: shengbinmeng@gmail.com
description: Just write.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.shengbin.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: shengbinmeng
github_username:  shengbinmeng
author_name: Shengbin Meng

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

permalink: /posts/:title
timezone: Asia/Shanghai
defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
  -
    scope:
      path: "images"
    values:
      image: true

paginate: 10
excerpt_separator: <!--more-->